/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package producer

fun main(args: Array<String>) {

    Thread {
        val reader = StreamReader()
        val producer = Producer()

        while (true) {
            producer.kafkaWriter(reader.reader())
        }
    }.start()
}


